"""add simulation columns

Revision ID: 89cc77a9a89f
Revises: bc14b67a40d7
Create Date: 2025-12-16 15:40:16.369190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89cc77a9a89f'
down_revision: Union[str, None] = 'bc14b67a40d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('analysis_jobs', sa.Column('projected_gdp', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('analysis_jobs', sa.Column('social_stability', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('analysis_jobs', sa.Column('timeline_labels', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('progress_events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('progress_events', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('analysis_jobs', 'timeline_labels')
    op.drop_column('analysis_jobs', 'social_stability')
    op.drop_column('analysis_jobs', 'projected_gdp')
    op.drop_column('analysis_jobs', 'summary')
    # ### end Alembic commands ###
