"""initial_schema

Revision ID: aa6599cfaa16
Revises: 
Create Date: 2025-12-17 15:42:31.250935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'aa6599cfaa16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('depth', sa.String(length=20), server_default='standard', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='created', nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('entities_count', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(sa.text("ALTER TABLE analysis_jobs ALTER COLUMN entities_count SET DEFAULT '{\"actors\": 0,\"policies\": 0,\"outcomes\": 0,\"risks\": 0}'::jsonb"))
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_table('query_expansions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_query', sa.Text(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('expansions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_hash')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('fetch_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('graph_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoints_analysis_id'), 'checkpoints', ['analysis_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('is_in_knowledge_base', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_analysis_id'), 'documents', ['analysis_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Integer(), server_default=sa.text('50'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('merged_into', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("entity_type IN ('actor', 'policy', 'outcome', 'risk')", name='check_entity_type'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100', name='check_confidence_range'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merged_into'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_analysis_id'), 'entities', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index('ix_entities_is_resolved', 'entities', ['is_resolved'], unique=False)
    op.create_table('progress_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_events_analysis_id'), 'progress_events', ['analysis_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('extraction_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_analysis_id'), 'chunks', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_search_vector', 'chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100', name='check_rel_confidence_range'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'source_entity_id', 'target_entity_id', 'relationship_type', name='relationships_analysis_id_source_entity_id_target_entity_id_key')
    )
    op.create_index(op.f('ix_relationships_analysis_id'), 'relationships', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_entity_id'), 'relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_entity_id'), 'relationships', ['target_entity_id'], unique=False)
    op.create_table('entity_provenance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_provenance_chunk_id'), 'entity_provenance', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_entity_provenance_entity_id'), 'entity_provenance', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_provenance_entity_id'), table_name='entity_provenance')
    op.drop_index(op.f('ix_entity_provenance_chunk_id'), table_name='entity_provenance')
    op.drop_table('entity_provenance')
    op.drop_index(op.f('ix_relationships_target_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_analysis_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('ix_chunks_search_vector', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_embedding', table_name='chunks', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_analysis_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_progress_events_analysis_id'), table_name='progress_events')
    op.drop_table('progress_events')
    op.drop_index('ix_entities_is_resolved', table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_analysis_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_documents_analysis_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_checkpoints_analysis_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_table('sources')
    op.drop_table('query_expansions')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
