"""add document processing status

Revision ID: cf0193d2b676
Revises: b20cdd07059f
Create Date: 2025-12-23 16:48:24.802633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0193d2b676'
down_revision: Union[str, None] = 'b20cdd07059f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=True))
    op.add_column('documents', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('documents', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.alter_column('documents', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'processing_error')
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###
