"""make chunk analysis_id nullable

Revision ID: eddc1b69c903
Revises: cf0193d2b676
Create Date: 2025-12-23 17:33:40.344168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddc1b69c903'
down_revision: Union[str, None] = 'cf0193d2b676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
